# Generated by Django 3.1 on 2020-10-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20201017_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academy',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sports',
            options={'ordering': ['sports_name', 'sports_type']},
        ),
    ]
