# Generated by Django 3.1.2 on 2020-10-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_auto_20201025_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='img',
            field=models.ImageField(default='', upload_to='sports/pics'),
        ),
        migrations.AddField(
            model_name='sports',
            name='img',
            field=models.ImageField(default='', upload_to='sports/trainer'),
        ),
    ]
