# Generated by Django 3.1 on 2020-10-14 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(help_text='Enter brief desc of Fitness club(i.e gym/yoga)', max_length=1000)),
                ('address', models.TextField(help_text='Enter address of Fitness club(i.e gym/yoga)', max_length=1000)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200)),
                ('training_type', models.CharField(max_length=200)),
                ('fitness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.fitness')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exp', models.IntegerField()),
                ('fitness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness.fitness')),
            ],
        ),
    ]
