# Generated by Django 3.1 on 2020-10-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20201017_0456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitness',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='traininglevel',
            options={'ordering': ['training_name', 'training_type']},
        ),
    ]
