# Generated by Django 3.1.2 on 2020-10-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0005_auto_20201025_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yoga',
            name='img',
            field=models.ImageField(default='', upload_to='yoga/pics'),
        ),
    ]
